app/routes/profile.py
"""
Определение маршрутов для страницы профиля веб-приложения.
"""
import os
import bcrypt
from PIL import Image
from re import fullmatch
from datetime import datetime, timedelta
from markupsafe import escape
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, current_app
from flask_login import current_user
from sqlalchemy.exc import IntegrityError, SQLAlchemyError
from app.models import Groups_members, Groups, Users, Courses, Lessons, Tasks, Hometasks, Notifications, UsersInfo, Files, FavoritesCourses, Deadlines
from app.extensions import db
from app.static.python.identicons import generate_avatar

profile_bp = Blueprint('profile', __name__)


@profile_bp.route('/profile/<id>', methods=['GET', 'POST'])
def profile(id):

    user = Users.query.filter_by(id=id).first()
    # todo: добавить страницу с ошибкой "пользователь не найден"
    if user is None:
        user = current_user

    return redirect(url_for('profile.profile_info', id=user.id))


@profile_bp.route('/profile/<id>/info', methods=['GET', 'POST'])
def profile_info(id):
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    
    user = Users.query.filter_by(id=id).first()
    
    user_info = UsersInfo.query.filter_by(user_id=id).first()

    unread = len(db.session.query(Notifications).filter(Notifications.user_id == current_user.id, Notifications.unread == True).all())

    groups = db.session.query(Groups).join(Groups_members).filter(Groups_members.student_id == user.id, Groups.title != None).all()

    user_certificates = []

    for group in groups:
        course = db.session.query(Courses).filter(Courses.id == group.course_id).first()
        lessons = db.session.query(Lessons).filter(Lessons.course_id == course.id).all()
        tasks = []
        all_tasks_correct = True

        for lesson in lessons:
            tasks += db.session.query(Tasks).filter(Tasks.lesson_id == lesson.id).all()

        for task in tasks:
            hometask = db.session.query(Hometasks).filter(Hometasks.task_id == task.id, Hometasks.student_id == id).first()
            
            if not hometask or hometask.status not in ["correct", "incorrect"]:
                all_tasks_correct = False
                break

        if all_tasks_correct:
            user_certificates.append(course)
    
    return render_template("profile/info.html", current_user=current_user, user=user, user_info=user_info, user_certificates=user_certificates, unread=unread)


@profile_bp.route('/profile/<id>/groups', methods=['GET', 'POST'])
def profile_groups(id):

    user = Users.query.filter_by(id=id).first()

    groups = db.session.query(Groups).join(Groups_members).filter(Groups_members.student_id == user.id, Groups.title != None).all()

    result = dict.fromkeys(groups, [])
    unread = len(db.session.query(Notifications).filter(Notifications.user_id == current_user.id, Notifications.unread == True).all())

    for group in groups:

        result_list = []
        
        result_list.append(db.session.query(Users.id, Users.name).filter(Users.id == group.curator_id).first())
        course = db.session.query(Courses).filter(Courses.id == group.course_id).first()
        result_list.append((course.id, course.title))
        result_list.append(db.session.query(Users.id, Users.name)
                .join(Groups_members, Users.id == Groups_members.student_id)
                .filter(Groups_members.group_id == group.id)
                .all())
        
        tasks = db.session.query(Tasks).join(Lessons, Lessons.id == Tasks.lesson_id).filter(Lessons.course_id == course.id).all()
        
        tasks_status = [db.session.query(Hometasks.status).filter(Hometasks.student_id == user.id, Hometasks.task_id == task.id).first() for task in tasks]
        tasks_status = [status[0] if status else "pending" for status in tasks_status]

        result_list.append(round(tasks_status.count('correct') / (len(tasks) if len(tasks) != 0 else 1) * 100, 2))
        result[group] = result_list
    
    return render_template("profile/groups.html", current_user=current_user, user=user, groups=result, unread=unread)


@profile_bp.route('/profile/<id>/settings', methods=['GET', 'POST'])
def profile_settings(id):
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    user = Users.query.filter_by(id=id).first()

    if current_user.id != user.id:
        return redirect(url_for('profile.profile', id=current_user.id))

    user_info = UsersInfo.query.filter_by(user_id=current_user.id).first()

    unread = len(db.session.query(Notifications).filter(Notifications.user_id == current_user.id, Notifications.unread == True).all())

    return render_template("profile/settings.html", current_user=current_user, user=user, user_info=user_info, unread=unread)


@profile_bp.route('/profile/<id>/courses', methods=['GET'])
def profile_courses(id):
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    
    user = Users.query.filter_by(id=id).first()
    # todo: добавить страницу с ошибкой "пользователь не найден"
    if user is None:
        user = current_user

    return redirect(url_for('profile.courses_taken', id=user.id))


@profile_bp.route('/profile/<id>/courses/taken', methods=['GET'])
def courses_taken(id):

    user = Users.query.filter_by(id=id).first()

    groups = db.session.query(Groups).join(Groups_members).filter(Groups_members.student_id == user.id).all()

    result = dict.fromkeys(groups, [])
    unread = len(db.session.query(Notifications).filter(Notifications.user_id == current_user.id, Notifications.unread == True).all())

    for group in groups:

        result_list = []
        
        course = db.session.query(Courses).filter(Courses.id == group.course_id).first()
        result_list.append((course.id, course.title, course.description))
        
        tasks = db.session.query(Tasks).join(Lessons, Lessons.id == Tasks.lesson_id).filter(Lessons.course_id == course.id).all()

        tasks_status = [db.session.query(Hometasks.status).filter(Hometasks.student_id == user.id, Hometasks.task_id == task.id).first() for task in tasks]
        tasks_status = [status[0] if status else "pending" for status in tasks_status]        

        result_list.append(round(tasks_status.count('correct') / (len(tasks) if len(tasks) != 0 else 1) * 100, 2))
        result[group] = result_list

    return render_template("profile/courses_taken.html", current_user=current_user, user=user, groups=result, unread=unread)


@profile_bp.route('/profile/<id>/courses/favorites', methods=['GET'])
def courses_favorites(id):
    
    user = Users.query.filter_by(id=id).first()
    
    courses = db.session.query(Courses).join(FavoritesCourses).filter(FavoritesCourses.user_id == id).all()

    unread = len(db.session.query(Notifications).filter(Notifications.user_id == current_user.id, Notifications.unread == True).all())

    return render_template("profile/courses_favorites.html", current_user=current_user, user=user, courses=courses, unread=unread)


@profile_bp.route("/profile/<id>/tasks", methods=["GET"])
def profile_tasks(id):
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))
    
    user = Users.query.filter_by(id=id).first()
    # todo: добавить страницу с ошибкой "пользователь не найден"
    if user is None:
        user = current_user

    if current_user.id != user.id:
        return redirect(url_for('profile.profile', id=current_user.id))

    return redirect(url_for('profile.tasks_pending', id=user.id))


@profile_bp.route("/profile/<id>/tasks/pending", methods=["GET"])
def tasks_pending(id):
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    user = Users.query.filter_by(id=id).first()

    if current_user.id != user.id:
        return redirect(url_for('profile.profile', id=current_user.id))
    
    tasks = db.session.query(Tasks).join(Lessons, Tasks.lesson_id == Lessons.id).join(Courses, Lessons.course_id == Courses.id).join(Groups, Groups.course_id == Courses.id).join(Groups_members, Groups_members.group_id == Groups.id).filter(Groups_members.student_id == id).all()
    
    unread = len(db.session.query(Notifications).filter(Notifications.user_id == current_user.id, Notifications.unread == True).all())

    tasks_info = {}

    for task in tasks:
        lesson = db.session.query(Lessons).filter_by(id=task.lesson_id).first()

        course = db.session.query(Courses).filter_by(id=lesson.course_id).first()

        group = db.session.query(Groups).join(Groups_members, Groups.id == Groups_members.group_id).filter(Groups.course_id == course.id, Groups_members.student_id == id).first()

        deadlines = db.session.query(Deadlines).filter_by(group_id=group.id, lesson_id=lesson.id).first()

        hometask = db.session.query(Hometasks).filter_by(task_id=task.id, student_id=id).first()  

        if not hometask:
            hometask = Hometasks(
                task_id=task.id,
                student_id=current_user.id,
                title=None,
                text=None,
                status='pending'
            )
            db.session.add(hometask)
            db.session.commit()

        if hometask.status == 'pending':  
            tasks_info[task] = (course, lesson, deadlines, hometask)

    far_future_date = datetime.now() + timedelta(days=365*100)
    tasks_info = dict(sorted(tasks_info.items(), key=lambda item: item[1][2].deadline.replace(tzinfo=None) if item[1][2] else far_future_date))

    return render_template("profile/tasks_pending.html", current_user=current_user, user=user, tasks_info=tasks_info, unread=unread)


@profile_bp.route("/profile/<id>/tasks/revision", methods=["GET"])
def tasks_revision(id):
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    user = Users.query.filter_by(id=id).first()

app/templates/profile/courses.html
{% extends 'profile/profile.html' %} 

{% block profile_content %}

<div class="d-flex gap-2">
  <a class="btn btn-light flex-fill {% if request.path == url_for('profile.courses_taken', id=user.id) %}active{% endif %}" type="button" href="{{ url_for('profile.courses_taken', id=user.id) }}">{% if current_user.id == user.id %}Прохожу{% else %}Проходит{% endif%}</a>
  <a class="btn btn-light flex-fill {% if request.path == url_for('profile.courses_favorites', id=user.id) %}active{% endif %}" type="button" href="{{ url_for('profile.courses_favorites', id=user.id) }}">Избранные</a>
</div>

{% block courses_content %}
{% endblock %}

{% endblock %}

app/templates/profile/courses_favorites.html
{% extends 'profile/courses.html' %} 

{% block courses_content %}

<div class="custom-form content" id="groups-container">
    {% for course in courses %}
    <div class="card mt-2 group-card">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h3 class="search_field"><a href="#" class="nounderline search_field">{{ course.title }}</a></h3>
          {% if current_user.id == user.id %}
          <div class="dropdown">
            <button class="btn btn-link pull-right nav-link" data-bs-toggle="dropdown">
              <span class="material-symbols-outlined"> more_vert </span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><button class="dropdown-item favorite_toggle" data-course-id="{{ course.id }}" data-event="delete">Удалить из избранного</button></li>
            </ul>
          </div>
          {% endif %}
        </div>
        <p>{{ course.description }}</p>
        <span>
            Цена курса: {% if course.price %} {{ course.price }} руб. {% else %} бесплатный {% endif %}
        </span>
      </div>
    </div>
    {% endfor %}
  </div>

{% endblock %}

app/templates/profile/courses_taken.html
{% extends 'profile/courses.html' %} 

{% block courses_content %}

<div class="custom-form content" id="groups-container">
    {% for group, value in groups.items() %}
    <div class="card mt-2 group-card">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h3 class="search_field"><a href="#" class="nounderline search_field">{{ value[0][1] }}</a></h3>
          {% if current_user.id == user.id %}
          <div class="dropdown">
            <button class="btn btn-link pull-right nav-link" data-bs-toggle="dropdown">
              <span class="material-symbols-outlined"> more_vert </span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><button class="dropdown-item favorite_toggle" data-course-id="{{ value[0][0] }}" data-event="add">Добавить курс в избранное</button></li>
            </ul>
          </div>
          {% endif %}
        </div>
        <p>{{ value[0][2] }}</p>
        <span>Прогресс по курсу:</span>
        <div class="progress" role="progressbar" aria-label="Basic example" aria-valuenow="{{value[1]}}" aria-valuemin="0" aria-valuemax="100">
          <div class="progress-bar" style="width: {{ value[1] }}%">
            {{value[1]}}%
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
</div>
  
<script>
</script>

{% endblock %}

app/templates/profile/groups.html
{% extends 'profile/profile.html' %}

{% block profile_content %}
<h1>Группы</h1>
<div class="d-flex input-group w-auto">
  <input id="search-input" type="search" class="form-control" placeholder="Название группы/курса" aria-label="Search" aria-describedby="search-addon"/>
  <button class="input-group-text border-1">
    <span class="material-symbols-outlined"> search </span>
  </button>
</div>
<div class="custom-form content" id="groups-container">
  {% for group, value in groups.items() %}
  <div class="card mt-2 group-card">
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <h3 class="search_field">{{ group.title }}</h3>
        {% if current_user.id == user.id %}
        <div class="dropdown">
          <button class="btn btn-link pull-right nav-link" data-bs-toggle="dropdown">
            <span class="material-symbols-outlined"> more_vert </span>
          </button>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><button class="dropdown-item favorite_toggle" data-course-id="{{ value[1][0] }}" data-event="add">Добавить курс в избранное</button></li>
            <li><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#adviceModal_{{ group.id }}">Запросить консультацию</button></li>
            <li><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#individualModal_{{ group.id }}">Запросить индивидуальный график обучения</button></li>
          </ul>
        </div>
        {% endif %}
      </div>

      <div class="modal fade" id="adviceModal_{{ group.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="staticBackdropLabel">Запрос консультации</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p> Ваше имя: {{ current_user.name }} </p>
              <p> Ваша группа: {{ group.title }} </p>
              <p> Курс: {{ value[1][1] }} </p>
              <div>
                <label for="message-text" class="col-form-label">Опишите запрос:</label>
                <textarea class="form-control" id="message-text"></textarea>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
              <button type="button" class="btn btn-primary send-button" data-bs-dismiss="modal" data-group-id="{{ group.id }}" data-course-id="{{ value[1][0] }}" data-type="adviceModal">Отправить</button>
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="individualModal_{{ group.id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="staticBackdropLabel">Запрос индивидуального графика</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p> Ваше имя: {{ current_user.name }} </p>
              <p> Ваша группа: {{ group.title }} </p>
              <p> Курс: {{ value[1][1] }} </p>
              <div>
                <label for="message-text" class="col-form-label">Опишите причины запроса:</label>
                <textarea class="form-control" id="message-text"></textarea>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
              <button type="button" class="btn btn-primary send-button" data-bs-dismiss="modal" data-group-id="{{ group.id }}" data-course-id="{{ value[1][0] }}" data-type="individualModal">Отправить</button>
            </div>
          </div>
        </div>
      </div>

      <span>
        Куратор: <a href="#" class="nounderline">{{ value[0][1] }}</a>
      </span>
      <br />
      <span>
        Курс: <a href="#" class="nounderline search_field">{{ value[1][1] }}</a>
      </span>
      <br />
      <span>
        Студенты: 
        {% for student in value[2] %}
        <a href="{{ url_for('profile.profile_info', id=student.id) }}" class="nounderline">{{ student.name }}</a>
        {% if not loop.last %}, {% endif %} 
        {% endfor %}
      </span>
      <br />
      <span>Прогресс по курсу:</span>
      <div class="progress" role="progressbar" aria-label="Basic example" aria-valuenow="{{value[3]}}" aria-valuemin="0" aria-valuemax="100">
        <div class="progress-bar" style="width: {{ value[3] }}%">
          {{value[3]}}%
        </div>
      </div>
    </div>
  </div>
  {% endfor %}

  <div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="successModalLabel">Сообщение отправлено</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Ваше сообщение было успешно отправлено куратору группы.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        </div>
      </div>
    </div>
  </div>

</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var searchInput = document.getElementById('search-input');
        var groupsContainer = document.getElementById('groups-container');

        searchInput.addEventListener("input", function() {
            var searchTerm = this.value.toLowerCase();
            var groupCards = groupsContainer.getElementsByClassName('group-card');

            for (var i = 0; i < groupCards.length; i++) {
                var searchFields = groupCards[i].getElementsByClassName('search_field');
                var isMatch = false;

                for (var j = 0; j < searchFields.length; j++) {
                    if (searchFields[j].innerText.toLowerCase().includes(searchTerm)) {
                        isMatch = true;
                        break;
                    }
                }

                if (isMatch) {
                    groupCards[i].style.display = 'block';
                } else {
                    groupCards[i].style.display = 'none';
                }
            }

        });

        var successModal = new bootstrap.Modal(document.getElementById('successModal'));

        var sendButtons = document.querySelectorAll('.send-button')
        sendButtons.forEach(button => {
          button.addEventListener('click', event => {
            event.preventDefault();

            var modalContent = event.target.closest('.modal-content');
            var messageText = modalContent.querySelector('textarea').value;
            var groupId = button.getAttribute('data-group-id');
            var courseId = button.getAttribute('data-course-id');


            fetch('/profile/send_request', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                group_id: groupId,
                course_id: courseId,        
                message_text: messageText,
                data_type: button.getAttribute('data-type')
              })
            })
              .then(response => response.json())
              .then(data => {
                successModal.show();
              })
              .catch(error => {
                console.error('Ошибка на сервере:', error);
              });

          });
        });

    });
</script>

{% endblock %}

app/templates/profile/hometask_view.html
{% extends 'profile/profile.html' %} 

{% block profile_content %}

<h3>{{ task.title }}</h3>
<p>{{ task.description }}</p>
{% if task_files %}
<label>Прикрепленные файлы:</label>
{% endif %}
{% for file in task_files %}
<div class="mb-3">
    <div class="attached-file">
        <a href="{{ url_for('static', filename='files/' + file.id|string) }}" download="{{ file.name }}">
            <i class="fa-solid fa-file-arrow-down"></i> {{ file.name }}
        </a>
    </div>
</div>
{% endfor %}

<h3>Домашнее задание</h3>
<div class="card-body">
    <h4>{{ hometask.title }}</h4>
    <p>{{ hometask.text }}</p>
    {% if hometask_files %}
    <label>Прикрепленные файлы:</label>
    {% endif %}
    {% for file in hometask_files %}
    <div class="mb-3">
        <div class="attached-file d-flex align-items-center mt-2">
            <a href="{{ url_for('static', filename='files/' + file.id|string) }}" download="{{ file.name }}">
                <i class="fa-solid fa-file-arrow-down"></i> {{ file.name }}
            </a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'main/base.html' %}

{% block content %}

<div class="d-flex align-items-stretch">
    <section class="left-sidebar p-1">
        <div class="" style="width: 280px;">
            <ul class="nav nav-pills flex-column mb-auto">
                <li>
                    <a href="{{ url_for('profile.profile_info', id=user.id) }}"
                        class="d-flex nav-link align-items-center {% if request.path == url_for('profile.profile_info', id=user.id) %}active{% else %}link-body-emphasis{% endif %}">
                        <span class="material-symbols-outlined me-1">
                            info
                        </span>
                        Информация
                    </a>
                </li>
                <li>
                    <a href="{{ url_for('profile.profile_courses', id=user.id) }}"
                        class="d-flex nav-link align-items-center {% if request.path == url_for('profile.courses_taken', id=user.id) or request.path == url_for('profile.courses_favorites', id=user.id) %}active{% else %}link-body-emphasis{% endif %}">
                        <span class="material-symbols-outlined me-1">
                            school
                        </span>
                        Курсы
                    </a>
                </li>
                {% if current_user.id == user.id %}
                <li>
                    <a href="{{ url_for('profile.profile_tasks', id=user.id) }}"
                        class="d-flex nav-link align-items-center {% if request.path == url_for('profile.tasks_pending', id=user.id) or request.path == url_for('profile.tasks_revision', id=user.id) or request.path == url_for('profile.tasks_done', id=user.id) %}active{% else %}link-body-emphasis{% endif %}">
                        <span class="material-symbols-outlined me-1">
                            task
                        </span>
                        Задания
                    </a>
                </li>
                {% endif %}
                <li>
                    <a href="{{ url_for('profile.profile_groups', id=user.id) }}"
                        class="d-flex nav-link align-items-center {% if request.path == url_for('profile.profile_groups', id=user.id) %}active{% else %}link-body-emphasis{% endif %}">
                        <span class="material-symbols-outlined me-1">
                            groups
                        </span>
                        Группы
                    </a>
                </li>
                {% if current_user.id == user.id %}
                <li>
                    <a href="{{ url_for('profile.profile_settings', id=user.id) }}"
                        class="d-flex nav-link align-items-center {% if request.path == url_for('profile.profile_settings', id=user.id) %}active{% else %}link-body-emphasis{% endif %}">
                        <span class="material-symbols-outlined me-1">
                            settings
                        </span>
                        Настройки
                    </a>
                </li>
                {% endif %}

            </ul>

        </div>
    </section>
    <div class="container ms-4">

        {% block profile_content %}
        {% endblock %}

    </div>
</div>


<script>

    document.addEventListener('DOMContentLoaded', function () {

        var FavoriteToggleLinks = document.querySelectorAll('.favorite_toggle')
        FavoriteToggleLinks.forEach(link => {
            link.addEventListener('click', event => {
                event.preventDefault();

                var courseId = link.getAttribute('data-course-id');
                var toggleEvent = link.getAttribute('data-event');
                
                if (toggleEvent === 'add') {
                    fetch('/profile/favorite_toggle', {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            course_id: courseId
                        })
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.category != 'success') {
                                showNotification(data.message, data.category);
                            } else {
                                window.location.reload();
                            }
                        })
                        .catch(error => {
                            console.error('Ошибка на сервере:', error);
                        });
                } else if (toggleEvent === 'delete') {
                    fetch('/profile/favorite_toggle', {
                        method: 'DELETE',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            course_id: courseId
                        })
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.category != 'success') {
                                showNotification(data.message, data.category);
                            } else {
                                window.location.reload();
                            }
                        })
                        .catch(error => {
                            console.error('Ошибка на сервере:', error);
                        });
                }

            });
        });
        
    });

</script>


{% endblock %}

app/templates/profile/tasks.html
{% extends 'profile/profile.html' %} 

{% block profile_content %}

<div class="d-flex gap-2">
  <a class="btn btn-light flex-fill {% if request.path == url_for('profile.tasks_pending', id=user.id) %}active{% endif %}" type="button" href="{{ url_for('profile.tasks_pending', id=user.id) }}">Текущие</a>
  <a class="btn btn-light flex-fill {% if request.path == url_for('profile.tasks_revision', id=user.id) %}active{% endif %}" type="button" href="{{ url_for('profile.tasks_revision', id=user.id) }}">На проверке</a>
  <a class="btn btn-light flex-fill {% if request.path == url_for('profile.tasks_done', id=user.id) %}active{% endif %}" type="button" href="{{ url_for('profile.tasks_done', id=user.id) }}">Завершенные</a>
</div>

{% block tasks_content %}
{% endblock %}

{% endblock %}

app/templates/profile/tasks_done.html
{% extends 'profile/tasks.html' %} 

{% block tasks_content %}

<div class="custom-form content" id="groups-container">
    {% for task, value in tasks_info.items() %}
    <div class="card mt-2 group-card">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h3 class="search_field"><a href="#" class="nounderline search_field">{{ task.title }}</a></h3>
        </div>
        <span>Курс: {{ value[0].title }}<span><br />
        <span>Урок: {{ value[1].title }}</span><br />
        <span>Результат: {% if value[3].status == 'correct' %} зачтено {% else %} не зачтено {% endif %} </span><br />
        <span>Домашнее задание: <a href="{{ url_for('profile.profile_hometask_view', id=current_user.id, task_id=value[3].id) }}">{{ value[3].title }}</a></span>
      </div>
    </div>
    {% endfor %}
</div>

{% endblock %}