app/routes/auth.py
from os.path import isfile
import bcrypt
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from flask_login import current_user, logout_user, login_user
from sqlalchemy import func
from sqlalchemy.exc import IntegrityError, SQLAlchemyError
from sqlalchemy.types import Numeric
from app.models import Users
from app.extensions import db
from app.static.python.identicons import generate_avatar

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        login_data = request.form.get('login')
        password_data = request.form.get('password')

        try:
            user = Users.query.filter_by(login=login_data).first()

            if not user:
                return jsonify({'category': 'warning', 'message': 'Ошибка в логине пользователя'})
            
            if user and bcrypt.checkpw(password_data.encode('utf-8'), user.password.encode('utf-8')):
                login_user(user)
                if not isfile(f"app/static/images/users/{current_user.login}.jpg"):
                    image = generate_avatar(current_user.login)
                    image.save(f'app/static/images/users/{current_user.login}.jpg', format='jpeg')
                return jsonify({'category': 'success', 'message': 'Успешный вход', 'redirect_url': url_for('profile.profile', id=user.id)})
            else:
                return jsonify({'category': 'warning', 'message': 'Ошибка пароля'})
        
        except IntegrityError as e:
            db.session.rollback() 
            print(str(e))
            return jsonify({'category': 'danger', 'message': 'Ошибка при входе в аккаунт'})
        
        except SQLAlchemyError as e:
            db.session.rollback() 
            print(str(e))
            return jsonify({'category': 'danger', 'message': 'Ошибка на сервере'})

    return render_template('auth/login.html', current_user=current_user)


@auth_bp.route('/register', methods=['POST', 'GET'])
def register():

    if request.method == 'POST':
        try:
            user_name = request.form.get('name')
            user_login = request.form.get('login')
            user_password = request.form.get('password')
            user_cpassword = request.form.get('cpassword')

            if user_password != user_cpassword:
                return jsonify({'category': 'warning', 'message': 'Пароли не совпадают'})
            
            if Users.query.filter_by(login=user_login).first():
                return jsonify({'category': 'warning', 'message': 'Пользователь с таким логином уже существует'})
            
            newuser = Users(
                name=user_name,
                login=user_login,
                password = bcrypt.hashpw(user_password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8'),
                role="student",
                balance=func.cast(0.0, Numeric(precision=10, scale=2)),
                scoring_system="points",
            )

            db.session.add(newuser)
            db.session.commit()

            image = generate_avatar(newuser.login)
            image.save(f'app/static/images/users/{newuser.login}.jpg', format='jpeg')

            login_user(newuser)

            return jsonify({'category': 'success', 'message': 'Пользователь создан', 'redirect_url': url_for('profile.profile', id=newuser.id)})
        
        except IntegrityError as e:
            db.session.rollback() 
            print(str(e))
            return jsonify({'category': 'danger', 'message': 'Ошибка при создании аккаунта'})
        
        except SQLAlchemyError as e:
            db.session.rollback() 
            print(str(e))
            return jsonify({'category': 'danger', 'message': 'Ошибка на сервере'})

    return render_template('auth/register.html', current_user=current_user)


@auth_bp.route('/logout')
def logout():
    """
    Функция обработки маршрута /logout, выполняющая выход пользователя из системы.
    """
    logout_user()
    return redirect(url_for('auth.login'))

app/routes/main.py
"""
Определение маршрута для главной страницы веб-приложения.
"""
from flask import Blueprint, render_template
from flask_login import current_user
from app.models import Notifications
from app.extensions import db

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    """
    Функция обработки маршрута '/', отображающая главную страницу приложения.
    Происходит подсчет количества непрочитанных уведомлений для текущего пользователя, 
    если он аутентифицирован.
    """
    
    unread = len(db.session.query(Notifications).filter(Notifications.user_id == current_user.id, Notifications.unread == True).all()) if current_user.is_authenticated else 0

    return render_template("main/index.html", current_user=current_user, unread=unread)

app/templates/main/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="precontent" href="https://fonts.googleapis.com">
  <link rel="precontent" href="https://fonts.gstatic.com" crossorigin="">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=PT+Serif&display=swap">
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://kit.fontawesome.com/53e8dff0f9.js" crossorigin="anonymous"></script>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>

  <script src="/static/js/notifications.js"></script>

  {% include "main/navbar.html" %}
  <div class="container">
    <div id="notification-container" class="m-auto"></div>
    <br /> 
    {% block content %}
    {% endblock %}
  </div>
  {% include "main/footer.html" %}


</body>

</html>

app/templates/main/footer.html
<footer class="text-body-secondary py-3">
    <div class="container">
        <div class="border-top d-flex justify-content-center py-3 text-secondary">
            EN-YSolutions, 2024
        </div>
    </div>
</footer>

app/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}



{% endblock %}

app/templates/main/navbar.html
<header class="p-3">
    <div class="container">
        <nav
            class="navbar border-bottom border-body d-flex align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class=" d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
                <a class="navbar-brand me-lg-auto" href="{{ url_for('main.index') }}">Образовательный портал</a>
            </a>
            <ul class="nav">

                {% if current_user.is_authenticated %}
                <a href="{{ url_for('profile.notifications', id=current_user.id) }}"
                    class="d-block link-body-emphasis text-decoration-none position-relative">
                    <span class="material-symbols-outlined" style="font-size: 34px;">
                        notifications
                    </span>
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill text-bg-info"
                        id="navbar_notifications">
                        {{ unread }}
                        <span class="visually-hidden">Непрочитанные сообщения</span>
                    </span>
                </a>
                {% endif %}
                <li class="nav-item dropdown ms-4">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none" data-bs-toggle="dropdown">
                        {% if current_user.is_authenticated %}
                        <img src="{{ url_for('static', filename='images/users/{}.jpg'.format(current_user.login)) }}" alt="mdo"
                            width="34" height="34" class="rounded-circle border border-secondary">
                        {% else %}
                        <span class="material-symbols-outlined" style="font-size: 34px;">
                            account_circle
                        </span>
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu">
                        {% if current_user.is_authenticated %}
                        <li><a class="dropdown-item"
                                href="{{ url_for('profile.profile', id=current_user.id, menu='info') }}"><i class="fa-solid fa-user"></i> Студент</a></li>
                        <li><a class="dropdown-item" href="#"><i class="fa-solid fa-message"></i> Сообщения</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}"><i class="fa-solid fa-right-from-bracket"></i> Выход</a></li>
                        {% else %}
                        <li><a class="dropdown-item" href="{{ url_for('auth.login') }}">Вход</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('auth.register') }}">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</header>